MacOS Monterey support
OpenImageDebugger/OpenImageDebugger pull request #54
Opened 2021-11-17 11:29 UTC by TohaKi11

Fixed things that were making problems during build on MacOS Monterey 12.0.1

CodeLLDB extension of Visual Studio Code has been used as a debugger

2021-11-17 12:46 UTC, TohaKi11 commented
I also updated the wiki page with installation instructions, since they were obsolete.

Please take a look and if they're fine - please clone them into the main repo:
https://github.com/TohaKi11/OpenImageDebugger/wiki/Building-on-MacOS

2021-11-17 13:58 UTC, brunoalr commented
Great PR, thanks! I'm reviewing it. So far I have mostly minor nitpicks. I wonder why Travis was not triggered :thinking:.

2021-11-17 14:53 UTC, TohaKi11 commented
It is worth triggering CI, since there are a huge amount of CMake changes

2021-11-17 14:57 UTC, brunoalr commented
> It is worth triggering CI, since there are a huge amount of CMake changes

Yes, I'm trying to check what's going wrong.

2021-11-24 16:58 UTC, brunoalr commented
Hi @TohaKi11 I'm currently on holidays without easy access to a laptop, so I cannot finish the review soon. In the meantime I pinged @csantosbh, I hope that he's not too busy now :)

2021-11-24 16:59 UTC, brunoalr requested changes

2021-11-24 16:59 UTC, brunoalr commented on common.cmake
> +if(NOT APPLE)
I guess there's no problem in changing the default for all OSes to /usr/local/bin for now. I will deal with Windows later anyways. Please do it so :)

2021-11-24 16:59 UTC, brunoalr commented on common.cmake
> +set(CMAKE_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX_DEFAULT} CACHE PATH "Install path" FORCE)
why FORCE?

2021-11-24 16:59 UTC, brunoalr commented on src/oidbridge/python3/CMakeLists.txt
> +    set(LLDB_PYTHON3_INFO "
nit: I would rename it to APPLE_LLDB_PYTHON3_INFO

2021-11-24 16:59 UTC, brunoalr commented on src/oidbridge/python3/CMakeLists.txt
> +    Take into consideration that your IDE may use custom lldb which differs from system-one.
nit: please add an extra level of indentation and keep the double quote together with the whole string.
something like:
```suggestion
    set(LLDB_PYTHON3_INFO
        "In order to properly compile the plugin, you must make sure it is linked against the same python lib binary used by lldb.
        Take into consideration that your IDE may use custom lldb which differs from system-one.
```

2021-11-24 16:59 UTC, brunoalr commented on src/oidbridge/python3/CMakeLists.txt
> +    Examine output and insert path to include directory here.
nit: same as comment above

2021-11-24 16:59 UTC, brunoalr commented on .gitignore
> +.DS_Store
what's this folder for? please add a short comment such as "used in macos builds"

2021-11-24 16:59 UTC, brunoalr commented on CMakeLists.txt
> +if(NOT APPLE)
thanks for keeping the code style consistent! now that I see this file again I think it is slight more clear to use IF(OS) instead of IF(NOT OS). If you would like to change it, I would appreciate :) (not needed now, though)

2021-11-24 17:01 UTC, brunoalr commented
I also published the initial minor nits I had. The main point is not there though. Basically I'm not sure if I like the idea of defaulting to error neither the idea of using a specific flag for CI. I'm open for discussions later on l.

2021-11-24 17:11 UTC, TohaKi11 commented on common.cmake
> +set(CMAKE_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX_DEFAULT} CACHE PATH "Install path" FORCE)
Maybe that's something that was left by mistake, I will remove that

2021-11-26 07:31 UTC, TohaKi11 commented on common.cmake
> +set(CMAKE_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX_DEFAULT} CACHE PATH "Install path" FORCE)
I double checked the behavior with and without FORCE and here are my findings:
- CMake sets default CMAKE_INSTALL_PREFIX value before reading CMakeLists.txt. On my machine it sets that to /usr/local
- When CMake reads this line in CMakeLists.txt it already has a value behind a variable and don't modifies it
- FORCE is needed to modify it even in that case
- But without additional check FORCE will be just changing any user input
- So, it is needed to be wrapped with CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT check
- See more details here: https://stackoverflow.com/a/39485990

Similar situation is with CMAKE_BUILD_TYPE variable. the solution is here:https://stackoverflow.com/a/48832234

2022-01-03 23:15 UTC, TohaKi11 commented
Hi @brunoalr and @csantosbh 

I've recently switched my working IDE to CLion and I see that the story with python library complexity continues.

CLion's lldb debugger uses `Python.framework` instead of `libpython*.dylib`.
In order to support that I added one more parameter for the user's input - `APPLE_LLDB_PYTHON3_FRAMEWORK_DIR`.

Now the user has two options: python library file OR framework directory.

Please check the PR and here is a link to the updated wiki page, feel free to cherry-pick it as well:
https://github.com/TohaKi11/OpenImageDebugger/wiki/Building-on-MacOS

Happy holidays,
Anton

2022-02-09 12:06 UTC, brunoalr commented
Hi @TohaKi11 I haven't forgotten you. It's just that life is a bit too busy lately. I will come back to you as soon as it is possible :) Thanks for your enthusiastic contributions! :D

2023-05-27 23:51 UTC, brunoalr commented
closing and reopening to trigger new CI

2023-05-29 20:17 UTC, brunoalr commented
after a long time, I came back :) I cherry-picked some commits that touched the code itself and I am still trying to figure out how to automatically ensure that OID is linked to the same python binaries as the ones used by lldb

2024-01-18 21:46 UTC, closed without merging